### ISSUE TITLE
Misleading scale at gyroscope sensor in wiki

### ISSUE THREAD

**Issue by ghost** [rushup/Kitra520#3]
The description of the full_scale field inside the sensor configuration (accelerometer/gyroscope/magnetometer) scales the gyroscope values by g. Due to the datasheet this value should be scaled in dps (degrees per second). Furthermore the datasheet of the sensor (LSM6DS3) mentions a scaling range between +-125 / +-245 / +- 500 / +- 1000 / +-2000 dps. It is a bit confusing how to set the five scales with just 2 bits.

**Comment by matteofumagalli1275** [comment]
Hi,

Thank you very much for the feedback.

I've just updated the Kitra-COM doc, currently supported dps are 245, 500, and 2000.

Regards.
