### ISSUE TITLE
Changing the baudrate is not acknowledged due to bad format

### ISSUE THREAD

**Issue by ghost** [rushup/Kitra520#4]
Changing baudrate of the mcu always responds 'not acknoledged' due to bad format (k_output_nack error_code contains '1' as value).

The following snippet is used to adjust the baudrate:
```
...
uint32_t baud_rate = 115200;
k_input_baud_rate msg = {K_INPUT_CHANGE_BAUD_RATE, baud_rate};
k_send_packet(&msg, 0);
...
```
I could not find a reason why the command should be in bad format.
Used firmware: HW:1, FW:1, EX:1

Thanks.

**Comment by matteofumagalli1275** [comment]
Hi,

Can you tell me what's acctually sent with that command?
Like putting a debug print inside `kitra_platform_send` callback.

I would like to understand if it's an issue related to the firmware or kitra-com-lib.

**Comment by ghost** [comment]
Hi,

here is the debug output from `kitra_platform_send`:
`$KITRA,511,115200*77`

I've done the following within the function:
```
void kitra_platform_send(char *buffer, uint32_t length)
{
    printf("%s", buffer);
    kitra_serial.serialPuts(buffer);
    k_unlock_tx();
}
```

I hope it helps somehow...

**Comment by matteofumagalli1275** [comment]
Can you try out the last firmware? [V1E3](https://github.com/rushup/Kitra520/blob/master/Firmware%20release/Application/Kitra_V1E3.bin)
The changelog [HERE](https://github.com/rushup/Kitra520/blob/master/Changelog.md) says that's an issue fixed from V1E2.

I have this application that works with firmware >= V1E2:
[https://github.com/rushup/kitra-com-test-mic](https://github.com/rushup/kitra-com-test-mic) and it does change the baudrate.

**Comment by ghost** [comment]
Oh, seems like I missed reading that file.
It would be great if you can add such information to the wiki as well.

Thanks for your help!
